server:
  port: 8800
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  #设置别名包扫描路径，通过该属性可以给包中的类注册别名
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
    map-underscore-to-camel-case: true
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.198.181.54:3306/guigu-oa?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: Dcp#7ujm
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 139.198.181.54
    port: 6379
    database: 0
    timeout: 1800000
    password: Dcp#7ujm
    jedis:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
